### ISSUE TITLE
Is there a way to make it automation?

### ISSUE THREAD

**Issue by ntgeralt** [17837697/QiangGuanDaAn#2]
Sorry my English is not good. 
At the moment, I can only do two copies on the phone & pc at the same time.Is there a simpler way to make it done?

**Comment by 17837697** [comment]
英语不好，汉语拼音也是可以的。
有个简单的办法可以多开
dingding网页版在其它地方登录的时候虽然会有强制退出的提示，并且无法直接点击了。但是由于hg平台是外挂的系统，和dingding网页不属于同一个域，所以信息其实并没有通知过去，hg的平台并不知道你其实已经在其它地方登录了。视频其实还是在正常播放的。甚至你在浏览器的调试模式里面，仍然可以直接用操控网页元素的方法正常使用hg平台的

**Comment by ntgeralt** [comment]
@17837697 您说的hg平台我不清楚指哪里呀。您能再说通俗一点如何多开吗 :)

**Comment by 17837697** [comment]
是的，开始播放视频后，不用管提示，不要动。直接在另一个网页登录重新打开另一门课程的视频即可。原来那门课的进度照样会走

**Comment by 17837697** [comment]
收到，没问题的话请回复，delete this issue

**Comment by ntgeralt** [comment]
@17837697 嗯 没问题了 谢谢提醒
